export const SECURITY_EVENT_TYPES = [
  "COPY_ATTEMPT",
  "PASTE_ATTEMPT",
  "CUT_ATTEMPT",
  "CONTEXT_MENU_ATTEMPT",
  "TAB_SWITCH",
  "WINDOW_BLUR",
  "FULLSCREEN_EXIT",
  "CAMERA_PERMISSION_DENIED",
  "CAMERA_UNAVAILABLE",
  "CAMERA_DISCONNECTED",
  "CAMERA_RECONNECTED",
  "RECORDING_STARTED",
  "RECORDING_STOPPED",
  "RECORDING_UPLOAD_FAILED",
  "FACE_DETECTED",
  "NO_FACE_DETECTED",
  "MULTIPLE_FACES_DETECTED",
  "FACE_DETECTION_UNAVAILABLE",
  "HEAD_LOOKING_LEFT",
  "HEAD_LOOKING_RIGHT",
  "HEAD_LOOKING_UP",
  "HEAD_LOOKING_DOWN",
  "PROLONGED_LOOKING_AWAY",
  "REPEATED_LOOKING_AWAY",
  "HEAD_MONITORING_UNAVAILABLE",
] as const;

export type SecurityEventType = (typeof SECURITY_EVENT_TYPES)[number];

export const SECURITY_SEVERITIES = ["LOW", "MEDIUM", "HIGH"] as const;
export type SecuritySeverity = (typeof SECURITY_SEVERITIES)[number];

export const SECURITY_RISK_LEVELS = ["LOW", "MEDIUM", "HIGH"] as const;
export type SecurityRiskLevel = (typeof SECURITY_RISK_LEVELS)[number];

/** Leave-style events that often fire together for one user action. */
export const LEAVE_SECURITY_EVENT_TYPES = [
  "TAB_SWITCH",
  "WINDOW_BLUR",
  "FULLSCREEN_EXIT",
] as const;

/** Counted toward Security Risk Level (not pure lifecycle/info). */
export const SECURITY_VIOLATION_EVENT_TYPES = [
  "COPY_ATTEMPT",
  "PASTE_ATTEMPT",
  "CUT_ATTEMPT",
  "CONTEXT_MENU_ATTEMPT",
  "TAB_SWITCH",
  "WINDOW_BLUR",
  "FULLSCREEN_EXIT",
  "CAMERA_PERMISSION_DENIED",
  "CAMERA_UNAVAILABLE",
  "CAMERA_DISCONNECTED",
  "RECORDING_UPLOAD_FAILED",
  "NO_FACE_DETECTED",
  "MULTIPLE_FACES_DETECTED",
  "HEAD_LOOKING_LEFT",
  "HEAD_LOOKING_RIGHT",
  "HEAD_LOOKING_UP",
  "HEAD_LOOKING_DOWN",
  "PROLONGED_LOOKING_AWAY",
  "REPEATED_LOOKING_AWAY",
] as const;

/** Face monitoring lifecycle / recovery (not counted as violations). */
export const FACE_INFO_EVENT_TYPES = [
  "FACE_DETECTED",
  "FACE_DETECTION_UNAVAILABLE",
  "HEAD_MONITORING_UNAVAILABLE",
] as const;
